### ISSUE TITLE
&amp; on flux:navlist.item

### ISSUE THREAD

**Issue by FortuneV13** [livewire/flux#529] opened 2024-10-24 12:47 UTC
`&amp;` is being added to the URL when using laravels route to define the URL in a navlist.item

`<flux:navlist.item href="{{route('salesmen-forecast.index',['user_id'=>$selectedUser,'page_category'=>'live_stats_turnover','year'=>date('Y')])}}"  > Salesmen Forecast</flux:navlist.item>`

results in:
`/salesmen-forecast?user_id=33&amp;page_category=live_stats_turnover&amp;year=2024`

**Comment by jeffchown** [comment] 2024-10-24 13:42
@FortuneV13 I believe this was fix a few versions ago.  What version are your Livewire and Flux? (`composer show`)

**Comment by jeffchown** [comment] 2024-10-24 13:56
Possibly

**Comment by joshhanley** [comment] 2024-10-25 01:37
@FortuneV13 for it to work correctly you do need to use the `:href="route()"` syntax. But I can confirm there is still a bug with `navlist.item`. I've submitted a PR with a fix.

**Comment by joshhanley** [comment] 2024-10-25 02:16
Turns out any component that accepts an href is having this issue. So I've submitted a PR #536 to Flux in addition to the PR I mentioned above to Flux Pro.

**Comment by calebporzio** [comment] 2024-10-25 12:31
Closing because this has been fixed.

**Closed by calebporzio** 2024-10-25 12:31 UTC

**Comment by joshhanley** [comment] 2024-10-25 23:44
@FortuneV13 Fixed as at Caleb's message. But is hasn't been released yet.
