### ISSUE TITLE
Rich text editor is empty when page refreshed

### ISSUE THREAD

**Issue by lloydowen** [livewire/flux#738] opened 2024-11-25 15:47 UTC
When using a element like this:
```html
<flux:editor wire:model="content" label="Content" description="Contract in Markdown "/>
```

However, if i refresh the page, or navigate via a traditional link the editor is initialised with no content.

When I navigate to a page with an editor using `wire:navigate`, the content displays as expected. 

I am filling the page on the mount method i.e.:
```php
  public function mount()
  {
      $this->fill($this->template->toArray());
  }
```
_At this point, `$content` is filled with valid HTML (previously saved with the editor)._

Which is filling the `$content` property on the livewire component:
```php
    #[Validate('required')]
    public ?string $content = '';
```

There are no errors in the console to report.

**Comment by jeffchown** [comment] 2024-11-25 17:46
@lloydowen Can you provide full code that can be copy/pasted to reproduce the issue?  Volt components are great, when possible.

**Comment by lloydowen** [comment] 2024-11-25 17:55
sure,

```php
<?php

use Livewire\Volt\Component;

new class extends Component {
    public $content = '<h1>Hello World</h1>';
}; ?>

<div>
    <flux:editor wire:model="content" />
</div>
```
results in:
![Image](https://github.com/user-attachments/assets/4a36e74a-daf3-4035-a2e1-4aa2fc81c8e7)

but adding `wire:model.live` for example:
```php
<?php

use Livewire\Volt\Component;

new class extends Component {
    public $content = '<h1>Hello World</h1>';
}; ?>

<div>
    <flux:editor wire:model.live="content" />
</div>
```
results in it working as expected:
![Image](https://github.com/user-attachments/assets/5a4d39bf-3fd5-4e3c-ba4a-95200a3545c0)

**Comment by jeffchown** [comment] 2024-11-25 18:02
@lloydowen I tried your first example, and can't recreate the issue.
With just `wire:model="content"`, it works for me:

![Image](https://github.com/user-attachments/assets/7187c93d-da16-4a26-9a79-8de34a409a47)

**Comment by lloydowen** [comment] 2024-11-25 18:23
Yes, i've tried that. 

Even if i output the content it's definitely there:

```php
<?php

use Livewire\Volt\Component;

new class extends Component {
    public string $content = '<h1>Hello World</h1>';
}; ?>

<div>
    <flux:editor wire:model="content"/>
    <div class="prose dark:prose-invert">
        {!! $content !!}
    </div>
</div>

```

![Image](https://github.com/user-attachments/assets/a1eecc9c-63a3-4d51-a688-4416149fb8ef)


 It only works with `.live` which i'll use for now. Sorry i don't have anymore logs to share. If i get some extra downtime i'll dive deeper into it, sharing in case it was a wider issue.

**Comment by jeffchown** [comment] 2024-11-25 18:39
@lloydowen Very strange.  Have you inspected the `flux:editor` using devtools to see if the content is maybe there but styled in a way that makes it invisible?

Good luck with the deeper dive.  I'm curious to hear what might be causing it.

**Comment by jeffchown** [comment] 2024-11-25 18:58
@lloydowen PS Plus make sure you are using Flux v1.0.27 as v1.0.26 had a dependency error which loaded an older version of Flux.

**Comment by sewid** [comment] 2024-11-26 07:10
I have the same problem when using a LivewireForm and the editor is wrapped in <form> tags. The editor remains empty. 
As an additional info, pressing a button with type="submit" does not trigger the form submission.
A button with a wire:click, calling the same "submit method" works without problems.

**Comment by lloydowen** [comment] 2024-11-27 09:12
This seems to be fixed since v1.0.28

**Comment by joshhanley** [comment] 2024-11-28 23:28
@lloydowen thanks for the report! I just tested this with your code provided above and it is working as expected for me on v1.0.28 without `.live` and with it.

I'm going to close this for now, but if you can find a way we can replicate the issue, please open a new issue and we'd be happy to investigate. Thanks!

**Comment by lloydowen** [comment] 2024-12-03 08:48
Yup, i still didn't get to the bottom of it. Reverted back to MDE for the time being.

**Comment by emkcloud** [comment] 2024-12-03 20:49
> Yup, i still didn't get to the bottom of it. Reverted back to MDE for the time being.


It seems that the issue is only related to the rendering of the component during the first HTTP request, specifically when it renders using the JSON snapshot of the HTML element. Afterward, even if the wire:model remains, making any method call is enough for the value to bind correctly. Additionally, using the Livewire component in lazy mode (<component lazy>) works properly because the refresh is handled via AJAX.

**Comment by joshhanley** [comment] 2024-12-03 22:01
@emkcloud if you can consistently replicate the problem, can you provide a Volt component that demonstrates the issue so we can investigate it? I will then re-open this issue. Thanks!

**Comment by danielrona** [comment] 2024-12-12 18:25
I have the same issue with 1.0.30 using links with wire:navigate will propogate the editor refreshing or directly accessing the component results in an empty editor.

Volt:
```php
<?php

use Livewire\Attributes\Validate;
use Livewire\Form;
use Livewire\Volt\Component;
use function Livewire\Volt\{form};

class TestForm extends Form
{
    #[Validate('required')]
    public string $content = '<h1>Hello World</h1>';
}


form(TestForm::class);

new class extends Component {
    public TestForm $form;
}; ?>

<div>
    <flux:editor wire:model="form.content"/>
    <div class="prose dark:prose-invert">
        {!! $form->content !!}
    </div>
</div>

```

If I setup a fresh install it works, so somewhere along the lines something got lost / changed / went missing, 
since I haven't published any custom blade files I wonder where/what could have change 
to cause this behavior.

Since I didn't want to use wire:model.live (wich also would have worked), I run wire:init with an empty body wich seems to temporary fix that too.

At some point I hope to find the solution to that

**Comment by jeffchown** [comment] 2024-12-12 19:31
@danielrona As the Volt component you provided is one "that works in a fresh install" - there's no way for anyone to reproduce/test the issue you are describing.

If you are able to provide a Volt component that consistently reproduces the issue, please start a new issue and follow the steps in the New Issue template.

**Comment by danielrona** [comment] 2024-12-12 19:44
@jeffchown I'm aware of that I was just pointing out that I also have the same issues that @lloydowen , @sewid  and @emkcloud reported, there's little to no point opening a new issue if I can't reproduce it in a fresh install now is there?

All of us seem to have solved it on their own ways with one going back to a different editor and one using wire:model.live, 
but four seperate incidents that can't be reproduced, suggests that the four of us might have something in common 
and I was hoping that the others might engage at some point to solve this together.

But together with the other three we just might find the common denominator and figure this out.

**Comment by sewid** [comment] 2024-12-16 07:57
@jeffchown I can reproduce the error, when I'm bundling Alpine manually as described here:
https://livewire.laravel.com/docs/alpine#manually-bundling-alpine-in-your-javascript-build

The default way works, but if I want to load custom Alpine plugins and switch to manual bundling, the editor is empty. The only way to bypass this is to use `<flux:editor wire:model.live="content" />`

**Comment by danielrona** [comment] 2024-12-16 12:44
@sewid nice catch, this indeed seems to be the issue

**Comment by joshhanley** [comment] 2024-12-17 21:39
Thanks everyone, the manually built Livewire/ Alpine seems to be the cause and I can replicate the issue.

To replicate:

1) Add this to your `js/app.js`
```js
import { Livewire, Alpine } from '../../vendor/livewire/livewire/dist/livewire.esm';

Livewire.start()
```
2) Include Livewire's script config and styles in `layouts/app.blade.php`
```blade
<html>
<head>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    @fluxStyles
    @livewireStyles
</head>
<body class="min-h-screen bg-white dark:bg-zinc-800">
    {{ $slot }}

    @fluxScripts
    @livewireScriptConfig 
</body>
</html>
```
3) Load the below Volt component and you should see "Hello world!" in the editor but it doesn't load. If you change it to `wire:model.live` then it loads.
```blade
<?php

use Livewire\Volt\Component;

new class extends Component {
    public $content = '';

    public function mount()
    {
        $this->content = '<p>Hello world!</p>';
    }
};
?>

<div>
    <flux:editor wire:model="content" label="Content" description="Contract in Markdown " />
    <div>Content: {{ $content }}</div>
</div>
```

**Comment by joshhanley** [comment] 2024-12-18 03:57
I've managed to work out what is going on with this and have submitted a PR with a fix!

**Closed** 2024-12-23 14:43 UTC

**Comment by pkeogan** [comment] 2025-05-05 22:06
@joshhanley this exact issue popped up for me in the past few weeks. I am building livewire in my `app.js` just like you provided in the example above 
```
import { Livewire, Alpine } from '../../vendor/livewire/livewire/dist/livewire.esm';

Livewire.start()
```
I wont beat a dead horse and post the setup, as its incidental to what you have in your post. 

If I go to a page via `wire:navigate` the editor loads correctly, but if I refresh the page its blank.

Where should I look for the setup issue?

**Comment by joshhanley** [comment] 2025-05-05 22:19
@pkeogan what patch version of Flux and Flux Pro are you on? Run `composer show -D` in your terminal to find the exact version.

**Comment by pkeogan** [comment] 2025-05-05 22:45
```
livewire/flux                 2.1.6   The official UI component library for Livewire.
livewire/flux-pro             2.1.6   The pro version of Flux, the official UI component library for Livewire.
livewire/livewire             3.6.3   A front-end framework for Laravel.
```

**Comment by joshhanley** [comment] 2025-05-05 23:05
@pkeogan hmm strange. It was all fixed. Are you able to create an example repo that demonstrates the issue so we can investigate it?
