### ISSUE TITLE
Input component does not correctly maps error to form Object

### ISSUE THREAD

**Issue by pbourdet** [livewire/flux#890] opened 2024-12-18 21:38 UTC
### Flux version

v1.1.0

### Livewire version

v3.5.17

### What is the problem?

When using a form object in a Livewire component, a Flux input wired to a form property do not display the validation errors

### Code snippets

Sample template : 

```
            <flux:input label="{{ __('Email') }}" description="We will very your email address"
                        name="email" type="email" autofocus placeholder="{{ __('Your email address') }}"
                        wire:model="form.email" required/>
            <flux:input label="{{ __('Username') }}" name="username" type="text"
                        placeholder="{{ __('Your username') }}"
                        wire:model="form.username" required/>
            <flux:input label="{{ __('Password') }}" name="password" type="password"
                        placeholder="{{ __('Your password') }}"
                        wire:model="form.password" required/>
            <flux:input label="{{ __('Confirm Password') }}" name="passwordConfirmation" type="password"
                        placeholder="{{ __('Confirm your password') }}"
                        wire:model="form.passwordConfirmation" required/>
``` 

With following livewire component/form : 

```
class Register extends Component
{
    public RegisterForm $form;

    public function register(): void
    {
        $this->form->validate();
    }
}

class RegisterForm extends Form
{
    public string $username = '';

    public string $email = '';

    public string $password = '';

    public string $passwordConfirmation = '';

    /** @return array<string, ValidationRule|array<int, mixed>|string> */
    public function rules(): array
    {
        return [
            'username' => ['required', 'string', 'min:2', 'max:40', 'unique:users'],
            'email' => ['required', 'string', 'lowercase', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'confirmed:passwordConfirmation', Password::defaults()],
        ];
    }
}
```

### How do you expect it to work?

I expect the validations errors to show under the input field when present.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment] 2024-12-18 21:56
@pbourdet If you do not provide a `label` attribute to `flux:input`, Flux assumes a minimalist form layout and does not display an error message.  This is by design.

See https://github.com/livewire/flux/issues/366

**Comment by pbourdet** [comment] 2024-12-18 22:01
Hello @jeffchown, sorry I removed to much code when opening the issue, but I do have a label in the actual code

**Comment by jeffchown** [comment] 2024-12-18 22:12
@pbourdet OK.  I don't see any validation rule(s) on your `$email` property:

`public string $email = '';`

should be 

```
#[Validate('required')]
public string $email = '';
```

**Comment by pbourdet** [comment] 2024-12-18 22:18
@jeffchown, I've put my actual code it should be clearer now ;)

**Comment by jeffchown** [comment] 2024-12-18 22:39
@pbourdet Please provide all of your code from the beginning next time.

Try removing the `name` attribute from each `flux:input`.  Flux will manage the `name` attribute automatically using the value you provide via `wire:model`.

**Comment by joshhanley** [comment] 2024-12-19 03:20
@pbourdet yeah @jeffchown is correct, the error will be pulling from the name attribute. So you should remove the name element (and Flux will add it for you with the same name as `wire:model`).

Going to close this. But feel free to open a new issue if you feel this doesn't fix it for you.

**Closed by joshhanley** 2024-12-19 03:20 UTC

**Comment by pbourdet** [comment] 2024-12-19 08:45
Hello, the solution provided by @jeffchown works great, thanks ! (I feel kinda stupid for not having thought of this on my own, to be honest 😅)

So no need for a new issue, thanks again and sorry for the bother
