### ISSUE TITLE
scrolling not working after closing modal

### ISSUE THREAD

**Issue by mauritskorse** [livewire/flux#358] opened 2024-10-08 10:18 UTC
Since I couldn't reopen the issue (#236), I created a new one. Hope that's okay.
I seem to have found why the issue occurs: Adding `flex` class to the modal causes this to happen. I guess adding a warning to the docs might be useful here.

> Okay, after some debugging, it seems that when adding flex classes to the modal various scrolling and clicking issues occur.
> My modal code from the example above had:
> 
> ```html
> <flux:modal name="instellingen" class="flex flex-col space-y-6 min-w-v-1/3 !max-w-v-4/5">
>         ...
> </flux:modal>
> ```
> 
> moving `flex flex-col` into a div within the modal seems to fix the scrolling issue
> ```html
> <flux:modal name="instellingen" class="min-w-v-1/3 !max-w-v-4/5">
>         <div class="flex flex-col space-y-6">
>                 ...
>         </div>
> </flux:modal>
> ```
>  

 _Originally posted by @mauritskorse in [#236](https://github.com/livewire/flux/issues/236#issuecomment-2399427248)_

**Comment by calebporzio** [comment] 2024-10-13 00:28
Thanks for following up! This is so weird -  I pulled your code down and couldn't reproduce it for the life of me. I'm going to close this and call it a weird obscure thing that hopefully won't happen in other scenarios. But if it does, we'll revisit this. Thanks for the report and glad you found a workaround.

**Closed by calebporzio** 2024-10-13 00:28 UTC
