### ISSUE TITLE
flux:checkbox does not handle "required" attribute

### ISSUE THREAD

**Issue by ibnIrshad** [livewire/flux#182] opened 2024-09-30 11:02 UTC
If I have the following code `<flux:checkbox name="tos" required/>` I expect that the `<input>` will have the "required" attribute so the browser will not allow form submission on the client side. However it does not appear that the required attribute is set on the `<input>` element. 

This might be a problem with ALL flux input elements actually, not sure, didn't try.

**Comment by MartijnCuppens** [comment] 2024-10-01 08:31
I can confirm this. Tested with the following code:

```html
<form action="">
    <flux:checkbox required label="This field is required" />
    <flux:button type="submit">submit</flux:button>
</form>
```

This seems to be an issue with the radios too. Input, textarea & select seem to be fine.

**Comment by calebporzio** [comment] 2024-10-02 01:16
Thanks for this report. You are correct this isn't working. Checkboxes, radios, switches, radio-groups, listboxes, and comboboxes all won't honor native input APIs like `required` because they aren't native inputs themselves.

For now, I'm going to close this, but will keep an eye on demand for supporting SOME kind of `required` prop. Of course, the current solution would be to do server-side validation.

THanks

**Closed by calebporzio** 2024-10-02 01:16 UTC
