### ISSUE TITLE
icons not displaying

### ISSUE THREAD

**Issue by saferecruits** [livewire/flux#659] opened 2024-11-13 11:31 UTC
Hello,

I am unable to view icons in my flux components when used within the navbar template provided.
When i use the icon component individually I am able to view the icon.

Below is the code and also a screenshot of what my page displays.

<div>
        <flux:header container class="bg-zinc-50 dark:bg-zinc-900 border-b border-zinc-200 dark:border-zinc-700">
            <flux:sidebar.toggle class="lg:hidden" icon="bars-2" inset="left" />
    
            <flux:brand href="#" logo="https://fluxui.dev/img/demo/logo.png" name="Acme Inc." class="max-lg:hidden dark:hidden" />
            <flux:brand href="#" logo="https://fluxui.dev/img/demo/dark-mode-logo.png" name="Acme Inc." class="max-lg:!hidden hidden dark:flex" />
    
            <flux:navbar class="-mb-px max-lg:hidden">
                
                <flux:navbar.item icon="home" href="#" current>
                <flux:icon.home />  
                    Home
                </flux:navbar.item>
                
                <flux:navbar.item icon="inbox" badge="12" href="#">Inbox</flux:navbar.item>
                <flux:navbar.item icon="document-text" href="#">Documents</flux:navbar.item>
                <flux:navbar.item icon="calendar" href="#">Calendar</flux:navbar.item>
    
                <flux:separator vertical variant="subtle" class="my-2"/>
    
                <flux:dropdown class="max-lg:hidden">
                    <flux:navbar.item icon-trailing="chevron-down">Favorites</flux:navbar.item>
    
                    <flux:navmenu>
                        <flux:navmenu.item href="#">Marketing site</flux:navmenu.item>
                        <flux:navmenu.item href="#">Android app</flux:navmenu.item>
                        <flux:navmenu.item href="#">Brand guidelines</flux:navmenu.item>
                    </flux:navmenu>
                </flux:dropdown>
            </flux:navbar>
    
            <flux:spacer />
    
            <flux:navbar class="mr-4">
                <flux:navbar.item icon="magnifying-glass" href="#" label="Search" />
                <flux:navbar.item class="max-lg:hidden" icon="cog-6-tooth" href="#" label="Settings" />
                <flux:navbar.item class="max-lg:hidden" icon="information-circle" href="#" label="Help" />
            </flux:navbar>
    
            <flux:dropdown position="top" align="start">
                <flux:profile avatar="https://fluxui.dev/img/demo/user.png" />
    
                <flux:menu>
                    <flux:menu.radio.group>
                        <flux:menu.radio checked>Olivia Martin</flux:menu.radio>
                        <flux:menu.radio>Truly Delta</flux:menu.radio>
                    </flux:menu.radio.group>
    
                    <flux:menu.separator />
    
                    <flux:menu.item icon="arrow-right-start-on-rectangle">Logout</flux:menu.item>
                </flux:menu>
            </flux:dropdown>
        </flux:header>
    
        <flux:sidebar stashable sticky class="lg:hidden bg-zinc-50 dark:bg-zinc-900 border-r border-zinc-200 dark:border-zinc-700">
            <flux:sidebar.toggle class="lg:hidden" icon="x-mark" />
    
            <flux:brand href="#" logo="https://fluxui.dev/img/demo/logo.png" name="Acme Inc." class="px-2 dark:hidden" />
            <flux:brand href="#" logo="https://fluxui.dev/img/demo/dark-mode-logo.png" name="Acme Inc." class="px-2 hidden dark:flex" />
    
            <flux:navlist variant="outline">
                <flux:navlist.item icon="home" href="#" current>Home</flux:navlist.item>
                <flux:navlist.item icon="inbox" badge="12" href="#">Inbox</flux:navlist.item>
                <flux:navlist.item icon="document-text" href="#">Documents</flux:navlist.item>
                <flux:navlist.item icon="calendar" href="#">Calendar</flux:navlist.item>
    
                <flux:navlist.group expandable heading="Favorites" class="max-lg:hidden">
                    <flux:navlist.item href="#">Marketing site</flux:navlist.item>
                    <flux:navlist.item href="#">Android app</flux:navlist.item>
                    <flux:navlist.item href="#">Brand guidelines</flux:navlist.item>
                </flux:navlist.group>
            </flux:navlist>
    
            <flux:spacer />
    
            <flux:navlist variant="outline">
                <flux:navlist.item icon="cog-6-tooth" href="#">Settings</flux:navlist.item>
                <flux:navlist.item icon="information-circle" href="#">Help</flux:navlist.item>
            </flux:navlist>
        </flux:sidebar>
    
        <flux:main container>
            <flux:heading size="xl" level="1">Good afternoon, Olivia</flux:heading>
    
            <flux:subheading size="lg" class="mb-6">Here's what's new today</flux:subheading>
    
            <flux:separator variant="subtle" />
        </flux:main>
</div>

![Image](https://github.com/user-attachments/assets/8aa75149-518a-49b8-836b-4b839f08bbff)

**Comment by jeffchown** [comment] 2024-11-13 13:39
@saferecruits Based on your screenshot, it looks like you may need to run `npm run build` or `npm run dev` to compile your assets

**Comment by saferecruits** [comment] 2024-11-13 14:02
Hello,I have done this already without any change.On 13 Nov 2024, at 14:39, Jeff Chown ***@***.***> wrote:﻿
@saferecruits Based on your screenshot, it looks like you may need to run npm run build or npm run dev to compile your assets

**Comment by jeffchown** [comment] 2024-11-13 14:34
@saferecruits Have you?:
- run `composer update` to update to the latest version of Flux?
- deleted then republished any Flux components you previous published?
- run `php artisan view:clear` 
- cleared your browser's cache?

**Comment by jeffchown** [comment] 2024-11-13 17:33
@saferecruits Once I edit your code to start with a `<flux:header>` (must have been left out of your copy/paste) and removed your extra 
`<flux:icon.home />` from the Home navbar item (guess you were testing the `<flux:icon...>`
The code works as expected for me.

Did you publish the Flux icons and/or move their directory?

**Comment by saferecruits** [comment] 2024-11-13 17:41
Hi Jeff,

I am using the code exactly as copied from the flux website.

I put in the <flux:icon.home /> to show that the icon is rendered in my environment.
However icons are not displayed when they are used in the opening tag of <flux:navbar.item icon="home" href="#" current>

**Comment by jeffchown** [comment] 2024-11-13 18:03
@saferecruits I don't believe the problem is the code.  I believe it has something to do with the assets.

As for you adding the `<flux:icon.home />` to show the icon is rendered in your environment, even that home icon looks to be too big to be the proper Flux default size.

If you view the page loading in your browser's devtools, are any of the files in red?

**Comment by saferecruits** [comment] 2024-11-13 19:05
Hi Jefff,

I uninstalled and reinstalled Tailwindcss upgraded to Laravel 11 and Livewire 3.4.

Everything seems fine now.

**Comment by jeffchown** [comment] 2024-11-13 19:08
Great! @saferecruits

**Comment by jeffchown** [comment] 2024-11-13 19:43
@saferecruits Don't forget to close this issue :)

**Closed** 2024-11-13 20:34 UTC
