### ISSUE TITLE
Problem with Modal when showing Toast and Dispatching Event

### ISSUE THREAD

**Issue by azizabbas** [livewire/flux#426] opened 2024-10-16 05:43 UTC
Hi,

This is in reply to the comment on following issue: https://github.com/livewire/flux/issues/402

I have created new gist that you can copy paste and reproduce that javascript error I mentioned in [#402](https://github.com/livewire/flux/issues/402).

https://gist.github.com/azizabbas/156bdb5c3639a724e85959ad7ad8aa5d

1. Click on Open Dialog button
2. Then, click **Cancel and Close** button inside Dialog
3. You can see javascript error inside browser console as shown below:

![Image](https://github.com/user-attachments/assets/016e0e4a-f37f-46c2-bc28-712a724471aa)

4. You can also watch this video on how this error is causing issues with registered Livewire Actions: https://github.com/user-attachments/assets/6048e43d-699f-463d-ad4d-59d5f11a3d65

I hope it helps to regenerate the bug.

Thanks

**Comment by calebporzio** [comment] 2024-10-17 16:02
Thanks for the report. I pulled it down locally and there was no console errors. Your GH gist worked fine.

After looking at the screenshot of your console errors - the errors have something to do with code specific to your project.

I suggest looking into `<template x-for="event in getEvents()" ...` - I have no idea if that is code from your project or a dependency that you have.

Going to close this as unable to reproduce - please re-submit if you can provide a code snippet I can copy/paste and reproduce this issue. Sorry I can't be of more help.

**Closed by calebporzio** 2024-10-17 16:02 UTC

**Comment by azizabbas** [comment] 2024-10-17 16:39
Hi Caleb.

Thank you so much for your reply, I have find out the problem and yes it was following package that was causing trouble:

https://github.com/wire-elements/wire-spy

I am commenting this may be it will help others.

Thanks again!
