### ISSUE TITLE
When a switch is in an array loop and an array item is removed, the switch causes a lockup - works fine if the switch is replaced with a standard html checkbox

### ISSUE THREAD

**Issue by igmltd** [livewire/flux#559] opened 2024-10-29 12:19 UTC
When a switch is in an array loop and an array item is removed, the switch causes a lockup - works fine if the switch is replaced with a standard html checkbox

**Pasteable volt component:**

route:

`Volt::route('/array', 'testarray');`

full example code:

```
<?php

use Livewire\Volt\Component;

new class extends Component {
    public $items = [
        [
            'enabled' => true,
            'shift_type' => 'Breakfast',
        ],
    ];

    public function deleteItem($index)
    {
        // Remove the item at the given index
        unset($this->items[$index]);

        // Re-index the array to maintain consistent keys
        $this->items = array_values($this->items);
    }

    public function addItem()
    {
        // Add a new empty item to the items array
        $this->items[] = $this->emptyItem();
    }

    public function emptyItem()
    {
        return [
            'enabled' => true,
            'shift_type' => '',
        ];
    }
}; ?>

<div>
    <flux:card class="max-w-2xl space-y-6">
        <div class="space-y-12 p-5">
            @foreach ($items as $index => $item)
                <div wire:key="items-{{ $index }}">
                    @if (! $loop->first)
                        <flux:separator class="my-5" />
                    @endif

                    <div class="relative">
                        <div class="absolute right-0 top-0">
                            <flux:button wire:click="deleteItem({{ $index }})" icon="trash" size="sm" class="ml-4 !text-red-800"></flux:button>
                        </div>
                        <div class="flex items-end justify-start">
                            <div class="w-full space-y-10">
                                <div class="flex items-center gap-x-6">
                                    <flux:switch wire:model.live="items.{{ $index }}.enabled" />

                                    <div class="flex w-full max-w-sm justify-start gap-x-3">
                                        <flux:select size="sm" wire:model="items.{{ $index }}.shift_type" placeholder="Select shift...">
                                            <flux:option>Breakfast</flux:option>
                                            <flux:option>Lunch</flux:option>
                                            <flux:option>Dinner</flux:option>
                                        </flux:select>
                                    </div>
                                </div>
                            </div>
                            <flux:spacer></flux:spacer>
                        </div>
                    </div>
                </div>
            @endforeach

            <flux:button wire:click="addItem" size="sm" icon="plus" class="mt-8">Add New</flux:button>
        </div>
    </flux:card>
</div>

```

<br/>

<br/>

**As you will see from the video below, when an item is removed, it locks up on the first click when a flux switch is present.**  

https://github.com/user-attachments/assets/c1421f84-93bb-4d45-ae69-dc8d7664cdaf

<br/>

<br/>

**Now with the flux switch replaced with a standard html  checkbox input, works fine.**

replaced the flux switch with   `   <input type="checkbox" wire:model="items.{{ $index }}.enabled" >`

**See video below, now works as expected.**

https://github.com/user-attachments/assets/bc64b9c8-50fb-4311-bb58-2351ca1cf251

**Other info:**

**- Also tested with a non volt component** 
**- Tested with flux checkbox, same issue as switch** 
**- Flux select does not seem to affect anything** 

Thanks in advance for looking into this.

**Comment by jeffchown** [comment] 2024-10-29 13:38
@igmltd I tried your code and experienced the same issue.  Very strange.

One thing I noticed is if I clicked to toggle the switch *first*, then clicked to delete the row, everything worked.
It seems to only be an issue when you click on the delete first.

**Comment by igmltd** [comment] 2024-10-29 13:54
> [@igmltd](https://github.com/igmltd) I tried your code and experienced the same issue. Very strange.
> 
> One thing I noticed is if I clicked to toggle the switch _first_, then clicked to delete the row, everything worked. It seems to only be an issue when you click on the delete first.

Thanks - 
To add to that i've also just noticed, if its false by default (setting it on the $items property and emptyItems() ), its deletes just fine, however the moment you interact with he switch to true, it causes the issue again.

**Comment by jeffchown** [comment] 2024-10-29 14:37
@igmltd Confirmed on this end.  That's strange... feels like there might be a clue in that...

**Comment by jeffchown** [comment] 2024-10-29 14:45
@igmltd If you delete any item other than the last, it seems to work OK (even if you toggle the switch to true first)

**Comment by jeffchown** [comment] 2024-10-29 15:03
@igmltd If you leave the switch set to false and then click delete, there is only 1 call to `livewire/update` via XHR (ajax).

If you toggle the switch to true, then click delete, there are, mysteriously, 2 calls to `livewire/update`:
- first, expectedly to `deleteItem`
![Image](https://github.com/user-attachments/assets/1258f499-008c-4293-b89c-2177cee1f2eb)

- second, unexpectedly, to toggle the switch (that is being deleted) back to false
![Image](https://github.com/user-attachments/assets/970dbd71-b86c-435c-b16c-8fa4728de398)

I think we may need some help from @calebporzio and @joshhanley on this one.

**Comment by igmltd** [comment] 2024-10-29 15:09
> [@igmltd](https://github.com/igmltd) If you delete any item other than the last, it seems to work OK (even if you toggle the switch to true first)

I get this if i try:


https://github.com/user-attachments/assets/3b5b709e-af97-4a6d-a790-24ba61675dda

**Comment by calebporzio** [comment] 2024-11-01 19:00
Wew, this was a bugger. Got it fixed though. The problem was a combination of things, but the root of it is:

Livewire looks for `wire:model` when it initializes elements and sets the input values. For native checkboxes/radios, this doesn't dispatch an input/change event. The non-native Flux checkboxes, radios, and switches, DO dispatch an input/change event anytime they are programmaticly set via `el.value = ?`.

BECAUSE of this behavior there's some weird stuff that's too annoying to explain about the way you're looping through the elements by index and what not.

Anyhow, it's totally fixed now with tests and will be in the next release. Thanks.

https://github.com/user-attachments/assets/f5eb143c-ae62-4364-a9f8-6b0d2c00a6bb

**Closed by calebporzio** 2024-11-01 19:00 UTC

**Comment by igmltd** [comment] 2024-11-01 21:03
thanks @calebporzio, you're just too much to take in - I appreciate you, much love.

**Comment by wevertondcl** [comment] 2024-11-02 16:17
Ohhh man, i just lost an entire day trying to figure it out haha, when will be the next release caleb? @calebporzio
