### ISSUE TITLE
Modal Scroll Issue: Background Scrollable & Dropdown Misalignment in Modal

### ISSUE THREAD

**Issue by lordisp** [livewire/flux#528] opened 2024-10-24 11:31 UTC
When a modal is open, the background remains scrollable, which causes additional issues such as the dropdown within the modal losing its correct position.

- The background page behind the modal is scrollable when the modal is open, instead of being locked.
- The dropdown within the modal loses its correct positioning when the background is scrolled.

**Steps to Reproduce**
1) Open the modal using the “Edit profile” button.
2) Scroll the background page while the modal is open.
3) Open the dropdown within the modal and scroll again.
4) Observe how the background continues to scroll and how the dropdown loses its position.

**Expected Behavior**
- When the modal is open, the background should be locked to prevent scrolling.
- The dropdown should maintain its correct position, even when scrolling occurs.

**Actual Behavior**

- The background page scrolls while the modal is open.
- The dropdown menu shifts out of place when the background scrolls, losing its intended position within the modal.

```blade
<div class="min-h-screen">
    <flux:modal.trigger name="edit-profile">
        <flux:button>Edit profile</flux:button>
    </flux:modal.trigger>

    <flux:modal name="edit-profile" variant="flyout" class="space-y-6">
        <div>
            <flux:heading size="lg">Update profile</flux:heading>
            <flux:subheading>Make changes to your personal details.</flux:subheading>
        </div>
        <div>
            <flux:dropdown>
                <flux:button icon-trailing="chevron-down">Options</flux:button>

                <flux:menu>
                    <flux:menu.item icon="plus">New post</flux:menu.item>
                </flux:menu>
            </flux:dropdown>
        </div>
    </flux:modal>
</div>
```
![Image](https://github.com/user-attachments/assets/d38c5337-5824-43f1-a6a2-064ee53ef2da)

Flux v1.0.18

**Comment by calebporzio** [comment] 2024-10-24 11:38
Closing because duplicate of #110 - we're planning a fix for this, thank you for the detailed report

**Closed by calebporzio** 2024-10-24 11:38 UTC
