### ISSUE TITLE
Checkbox state not correctly set when using `intended` redirect with Laravel

### ISSUE THREAD

**Issue by LasseRafn** [livewire/flux#608] opened 2024-11-05 21:27 UTC
Flux version: v1.0.20

I cannot provide code sample since it requires multiple steps, including auth or similar, but essentially when you have a checkbox with checked state as default (eg setting checked = true during Livewire mount), it doesn't get checked, IF the user comes from an redirect `intended`, eg from being prompted to log in.

Imagine this flow:

1. Open /admin/posts/1/edit
2. User not logged in, redirected to /login
3. Logs in, redirected back to /admin/posts/1/edit
4. Checkbox "Published" is not checked, despite actually being true
5. Refresh the page, checkbox is now correctly checked.

**Comment by ju5t** [comment] 2024-11-06 16:32
I tried to come up with a code sample, and although not strictly the same, I haven't been able to replicate it. It somehow feels like a caching thing. In the code sample below I do use `redirect()->intended()` but it lacks the `/login`-step.

```php
<?php
\Livewire\Volt\mount(function () {
    if (! session()->has('redirect')) {
        session()->flash('redirect');
        redirect()->intended('/');
    }

    $this->checked = true;
});

\Livewire\Volt\state([
    'checked' => false,
]);
?>

<div class="p-6">
    @session('redirect')
    <div>Redirected</div>
    @endsession
    <div>Value: @json($checked)</div>
    <flux:checkbox wire:model.boolean="checked" />
</div>
```

**Comment by calebporzio** [comment] 2024-11-15 12:44
I just tested this with a login flow and wasn't able to produce the bug

![Image](https://github.com/user-attachments/assets/35200346-63a8-46b6-b972-ebe833973643)

Closing this - please re-open if you can give us something to reliably reproduce. Thanks for helping on this @ju5t

**Closed by calebporzio** 2024-11-15 12:44 UTC
