### ISSUE TITLE
[Documentation] Typo

### ISSUE THREAD

**Issue by WorthLMS** [livewire/flux#30] opened 2024-09-24 05:36 UTC
URL: https://fluxui.dev/components/select

`<flex:option>Photography</flux:option>`

should be "flux:option" on first option, not flex

**Comment by skatecram** [comment] 2024-09-24 05:40
This issue is a duplicate of [#12](https://github.com/livewire/flux/issues/12).

**Comment by bensherred** [comment] 2024-09-24 06:44
Closed due to duplicate issue

**Closed by bensherred** 2024-09-24 06:44 UTC
