### ISSUE TITLE
Dark mode can't be turned off

### ISSUE THREAD

**Issue by bernhardh** [livewire/flux#855] opened 2024-12-12 17:44 UTC
### Flux version

v1.0.30

### Livewire version

v3.5.17

### What is the problem?

Since the latest update (v1.0.30), my site is stuck in dark mode, but I don't want this. I am not the only one with this problem, in discord chat, there is at least another user with a similar problem.

I know my browser preferences are set to "dark mode," but my client doesn't like dark mode and only wants the page to use standard styles.

Calling `window.Flux.dark = false;` is a hotfix, but not a real solution.

### Code snippets

I tried setting `darkMode: "selector" and `darkMode: false`, but nothing worked. The dark class is always being added to the body element.

### How do you expect it to work?

I expect, that `darkMode: false` or `darkMode: "selector"` is respected.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by calebporzio** [comment] 2024-12-12 17:45
What were you doing before to prevent the site from going into dark mode if the users OS is on dark mode?

**Comment by calebporzio** [comment] 2024-12-12 17:47
I don't want to introduce a break, so I'm sure we can find a solution, but when I thought about this, my understanding was that currently, because Flux uses .dark: utilities everywhere it would naturally go dark when the OS goes dark.

Or are you saying that you chose darkMode: 'selector' in tailwind for the purpose of DISABLING dark mode in your app? (by never adding a .dark class to body?)

**Comment by bernhardh** [comment] 2024-12-12 17:48
Nothing. It wasn't dark. I just upgraded

```
 - Upgrading livewire/livewire (v3.5.12 => v3.5.17): Extracting archive
  - Upgrading livewire/flux (v1.0.29 => v1.0.30): Extracting archive
  - Upgrading livewire/flux-pro (1.0.29 => 1.0.30): Extracting archive
```

and afterwards the page switched into darkmode. 

I tried it now out in inkognito mode and it is dark as well.

**Comment by seabasss** [comment] 2024-12-12 17:55
It's a breaking change that the app suddenly turns dark without asking for it. It shouldn't set a dark class to the body tag automatically. This should be opt in, even if you have dark classes in your html code.

I bet the latest update is great for some users, but we need to be able to control this manually.

**Comment by MCKLtech** [comment] 2024-12-12 18:00
Adding as this may be relevant, when I upgraded to 1.0.30, all my dropdowns in Tailwind e.g.

```
 <select id="team" name="team" x-model="team"
            class="mt-1 block w-full rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm">

        @foreach(auth()->user()->allTeams() as $team)
            <option value="{{$team->id}}">{{$team->name}}</option>
        @endforeach
    </select>
```

Have the select text forced to white, which I presume is because dark mode is being forced on them. As a result, they cannot be read unless they are clicked. Removing @fluxScripts fixes it, so it's being caused by Flux.

Flux components are not affected and dark mode works as expected.

**Comment by bernhardh** [comment] 2024-12-12 18:14
> I don't want to introduce a break, so I'm sure we can find a solution, but when I thought about this, my understanding was that currently, because Flux uses .dark: utilities everywhere it would naturally go dark when the OS goes dark.

Well, yes and no. There is a setting (at least in Chrome under linux) for this. Go to `chrome://flags/` and search for ` Auto Dark Mode for Web Contents`. For me, it was set to `default` (I haven't changed it). With this setting, the dark ` .dark:*` have done nothing until now. 

I just tried it out, by reverting the upgrade (going back to 1.0.29). And the page is back in white. Changing this setting to "enabled" forces the dark mode even on 1.0.29. 

![Image](https://github.com/user-attachments/assets/0f4f1848-6a2c-4aa2-8a84-8c3a4713d9c6)

**Comment by calebporzio** [comment] 2024-12-12 20:17
Ok, so I think the problem is folks are using `darkMode: 'selector'` as a way to kind of disable dark mode in Tailwind.

There is no official way in Tailwind to disable the handling of `dark:` variants. However, it will effectively disable them by passing an unrecognized string like `'none'`.

Therefore, I think I'm going to keep this behavior that is currently in Flux and recommend that people use the following Tailwind configuration line:

```html
module.exports = {
    darkMode: 'none',

    ...
}
```

**Comment by seabasss** [comment] 2024-12-12 20:26
I use `darkMode: 'selector'` and `<html class="{{ $theme ?? 'light' }}">` and it has worked great until now. I don't want to set it to `'none'`. Why automatically add the dark class to the body tag?

This is from the Tailwind documentation: `If you want to support toggling dark mode manually instead of relying on the operating system preference, use the selector strategy`. This is exactly how I want it to work. Please revert or support this.

**Comment by calebporzio** [comment] 2024-12-12 21:27
Ok, this should be fixed in the latest release. Try pulling down and trying again

**Comment by joshhanley** [comment] 2024-12-12 21:41
Just tested this and I was using `darkMode: 'selector'` to disable Flux's darkmode styles.

Have pulled v1.0.31, set `darkMode: null` in my `tailwind.config.js` and it works great. Dark mode is now disabled completely.

And there is the added benefit that my `app.css` was 100kb before and it's now 70kb 😁

**Comment by seabasss** [comment] 2024-12-12 21:50
> Ok, this should be fixed in the latest release. Try pulling down and trying again

Still dark mode and it adds `.dark` to the `body` tag automatically.

If I change from `darkMode: 'selector'`, I can no longer switch between light and dark manually based on the user's settings.

Let's say I have `$user->theme` and want this to decide if dark or light should be used? What's the new solution?

**Comment by iBotPeaches** [comment] 2024-12-12 22:06
I think enough folks are commenting, but latest release is also spamming a new console log :)

```
    // isUsingSelectorForDarkModeInTailwind
    console.log(result);
```

I was in the same boat of using `selector` unaware I was intentionally opting out of dark mode. Site looks like others in a half dark/light mode, which is odd considering I use like 90% of the flux components which I figured are dark mode supported.

<img width="1353" alt="Image" src="https://github.com/user-attachments/assets/4cdf051c-dd67-4372-a6a5-9af5f58315d1" />


No rush, I don't need to be on bleeding edge. I reverted and will revisit once this settles with either a forced disabling of dark mode or properly supporting it.

**Comment by joshhanley** [comment] 2024-12-13 00:06
@iBotPeaches thanks for reporting! We've removed it and tagged v1.0.32 🙂

**Comment by joshhanley** [comment] 2024-12-13 06:41
@seabasss you can still use your users settings to set which theme to display and make use of your existing theme switcher under user settings.

To do this you will need to set `darkMode: 'selector'` in your `tailwind.config.js`.

Then on an element somewhere in your layout:

```blade
@php($theme = 'light')
<div x-init="$flux.appearance = '{{ $theme ?? 'light' }}'"></div>
```

I recommend using a dedicated element for this, instead of putting it on the `<body>`, as putting Alpine on the `<body>` element means the whole DOM tree is initialised which isn't ideal.

Naturally you could replace the local `$theme` with the users preference, I just wanted to show the basic version first.

```blade
<div x-init="$flux.appearance = '{{ auth()->user?->theme ?? 'light' }}'"></div>
```

Hope this helps!

**Comment by MCKLtech** [comment] 2024-12-13 15:45
> To do this you will need to set `darkMode: 'selector'` in your `tailwind.config.js`.
> 
> Then on an element somewhere in your layout:
> 
> @php($theme = 'light')
> <div x-init="$flux.appearance = '{{ $theme ?? 'light' }}'"></div>
> I recommend using a dedicated element for this directly below the opening `<body>` tag, instead of putting it on the `<body>` element itself, as putting Alpine on the `<body>` element means the whole DOM tree is initialised which isn't ideal.

This fixed my problem. Thank you. It might be worth adding/highlighting in the docs.

**Comment by seabasss** [comment] 2024-12-13 16:52
> [@seabasss](https://github.com/seabasss) you can still use your users settings to set which theme to display and make use of your existing theme switcher under user settings.
> 
> To do this you will need to set `darkMode: 'selector'` in your `tailwind.config.js`.
> 
> Then on an element somewhere in your layout:
> 
> @php($theme = 'light')
> <div x-init="$flux.appearance = '{{ $theme ?? 'light' }}'"></div>
> I recommend using a dedicated element for this directly below the opening `<body>` tag, instead of putting it on the `<body>` element itself, as putting Alpine on the `<body>` element means the whole DOM tree is initialised which isn't ideal.
> 
> Naturally you could replace the local `$theme` with the users preference, I just wanted to show the basic version first.
> 
> <div x-init="$flux.appearance = '{{ auth()->user?->theme ?? 'light' }}'"></div>
> Hope this helps!

Thanks as always, Josh!

I wanted to share my thoughts because I still feel this change might not be the best direction. Here’s why: I’m a huge fan of dark mode. I use it in the OS, on my phone, and probably even in the browser. But “user first” doesn’t always mean giving users what they prefer in every context. For instance, I wouldn’t want to read news on a dark-themed site, nor do I expect Apple.com or Nike.com to adapt to my dark mode settings - it’s just not their brand. Similarly, my app was designed to be in light mode because that’s part of its identity. That said, I still want to let users enable dark mode manually via user settings - but only when logged in, not on the public pages.

Having a light/dark mode toggle always available feels right for something like the Flux demo page. But do users really want websites to dynamically switch themes based on the time of day or see a toggle in their UI all the time? How many people actually switch themes multiple times a day?

The suggested change also introduced a flicker on every page load, so I’ve had to keep my original code on the <html> tag to ensure it triggers before Alpine. Now, I also need to add extra code to every layout file.

Just my two cents :)

**Comment by igmltd** [comment] 2024-12-13 18:01
Great feature.
Just a note -  I think the .dark class added needs to be an optional thing rather than x-init="$flux.appearance = 'light' just to disable it - its another thing to remember, when you need it you'll look for it. maybe a tag, setting - not sure but something to say "i want flux to deal with the light settings" then add the dark class / local storage etc.

Thanks.

**Comment by joshhanley** [comment] 2024-12-13 21:10
@MCKLtech great that it solved your problem! Which part exactly fixed it for you? Or are you talking about my instructions how to manually set a theme from the backend? Just want to make sure I'm clear which part you are talking about, as the Tailwind config part should already be there, but if it's the rest of it then I can look at getting it added.

@seabasss no worries! For a bit of insight, it's a precursor to all of Flux's theming stuff. For themes to work properly there needed to be inbuilt support for Dark mode in Flux. I do hear what you're saying though and agree to a degree. But also believe if people want no dark mode at all, you disable it in your Tailwind config (which makes the compiled CSS smaller too) using `darkMode: null`. Or if you want it server configurable (ie user preferences or set a default), then something similar to what I posted should work.

Re the flicker, that is a good point. Yeah my solution doesn't account for handling it pre-load, so still manually outputting the dark class on the html or body tag for it to render with the correct theme, before Alpine/Flux javascript takes over, is probably a good idea. Then it doesn't fully reply on JS.

**Comment by igmltd** [comment] 2024-12-14 00:09
Hi @joshhanley, would it not be option to set the default to light, therefore the .dark class would not be there by default? I’m thinking then it wouldn’t interfere with any setup someone may have.

**Comment by joshhanley** [comment] 2024-12-14 00:58
@igmltd so at the moment what Flux is doing is detecting what the system default is, and applying that. The reason we need that is because we can't use `@media (prefers-color-scheme: dark)` as it messes up the styling, so Flux needs to detect it instead.

**Comment by bernhardh** [comment] 2024-12-15 15:46
I am not sure, but can I close this issue for now?

**Comment by joshhanley** [comment] 2024-12-15 21:46
@bernhardh yep I will close it. If anyone else has any further issues, please open up a new issue.

**Closed by joshhanley** 2024-12-15 21:46 UTC

**Comment by SilasOtoko** [comment] 2024-12-17 20:53
@joshhanley I'm wondering if it might be useful to make the fix more public, if that is the right word. I ended up here after troubleshooting the dark mode thing for a couple of hours, and only figured out it was coming from Flux when I was commenting out libraries one by one.

I didn't have anything in my project related to Dark Mode, including not specifying anything in my `tailwind.config.js` file, so I was very confused why `class="dark"` was being added automatically and turning all the text white regardless of not using any `dark:` prefixes anywhere in the project.

I wonder that others might also not realize this is coming from Flux and that they only need to update it.

**Comment by joshhanley** [comment] 2024-12-17 21:58
@SilasOtoko I'm not sure how to make it more public, it's documented here https://fluxui.dev/docs/installation#disabling-dark-mode. Is there anywhere else you were thinking?

**Comment by igmltd** [comment] 2024-12-17 22:46
> [@igmltd](https://github.com/igmltd) so at the moment what Flux is doing is detecting what the system default is, and applying that. The reason we need that is because we can't use `@media (prefers-color-scheme: dark)` as it messes up the styling, so Flux needs to detect it instead.

Thanks for the reply and insight - I do think it should be an optional thing - maybe activated by a tag to explicitly tell flux to manage dark mode in any way - if not left as if it was never there.

Some people might not even know flux has set it to system, while tailwind could be on selector - that could activate dark mode on a site without the developer intending or ever knowing.

Hope that makes sense.
