### ISSUE TITLE
Searchable input - wire:model

### ISSUE THREAD

**Issue by Delavor** [livewire/flux#205] opened 2024-10-01 09:01 UTC
I have searchable select, but there is no static options, there is foreach with data from database based on what you entered in the search input. It's working fine when you creating a new object but on edit there is in search input and option but it's not selected by default

**component**
```php
public function mount(Recipient $recipient)
    {
        [...]
        $this->searchedContractors = Arr::prepend([], $recipient->contractor);
        $this->contractor_name = $recipient->contractor->name;
        $this->contractor_id = $recipient->contractor_id;
        [...]
    }
```

**view**
```html
<flux:select
        label="{{ __('Kontrahent') }}"
        variant="listbox"
        searchable
        placeholder="{{ __('Wybierz kontrahenta') }}"
        wire:model="contractor_id"
    >
        <x-slot name="search">
            <flux:select.search placeholder="{{ __('Szukaj...') }}" wire:model="contractor_name" wire:keyup="search" />
        </x-slot>
        @foreach($searchedContractors as $contractor)
            <flux:option value="{{ $contractor->id }}">{{ $contractor->name }}</flux:option>
        @endforeach
    </flux:select>
```

**Comment by gaiustemple** [comment] 2024-10-01 10:00
This is likely a duplicate of #60

**Comment by joshhanley** [comment] 2024-10-02 07:44
@gaiustemple I think this is a separate issue (I helped @Delavor on discord). What they're hoping to achieve he is to set a default value for the select on mount of their Livewire component, but currently it seems that's not possible as the `wire:model` value isn't shown.

**Comment by calebporzio** [comment] 2024-10-03 23:18
Ah I see, yeah for now I'm going to say this is more of a feature request and close it until we run into more demand for this. Thanks for the report.

**Comment by KenGuggelmeyer** [comment] 2024-10-08 13:17
I actually disagree on this one. Showing the selected option is a core functionality of every dropdown/combobox. Now we have to click on the dropdown to show which option is selected. It just isn't shown on the render:

wire:model contains value 21:
![Image](https://github.com/user-attachments/assets/86ec5e47-9a1b-4a5e-b141-8b00a95d013c)

When opened
![Image](https://github.com/user-attachments/assets/c12a57a8-d556-4eaa-84ce-dda01c4ced6e)

**Comment by joshhanley** [comment] 2024-10-08 23:21
@calebporzio yeah I disagree with closing this too, as we should be able to pre-select data and have that shown, especially in an edit form. Going to re-open, but feel free to close again if you still think it's a feature request.

**Comment by calebporzio** [comment] 2024-10-13 13:45
Ok, I may have fixed this when fixing this issue: https://github.com/livewire/flux/issues/299

However, I'm closing this either way because I will need a better code sample to reproduce. Please, no Blade variables that aren't statically defined in the snippet so I can reproduce easily and help you. Thanks!

**Closed by calebporzio** 2024-10-13 13:45 UTC
