### ISSUE TITLE
Modal inside a tab freezes everything

### ISSUE THREAD

**Issue by Hesesses** [livewire/flux#556] opened 2024-10-28 22:59 UTC
I'm trying to add modal confirmation.

Sometimes when you click delete, the modal is shown but nothing works anymore (you cant click cancel or delete project, hover doesnt work)
Sometimes cancel and delete project buttons works on modal, but when you click one of those, the modal is closed but everything has stopped working, no hovers, click buttons doesnt work, cant change tab etc. No console errors.

Everything works when code related to modal is removed.

Code:

```
<div class="space-y-6">
    <flux:tab.group>
        <flux:tabs wire:model="trans" wire:click="changeTrans" class="overflow-x-auto">
            @foreach (['en','fi','es'] as $language)
                <flux:tab name="{{ $language }}">
                    {{ $language }}
                </flux:tab>
            @endforeach

        </flux:tabs>

        @foreach (['en','fi','es'] as $translation)
            <flux:tab.panel :name="$translation">

                <form wire:submit="saveTranslation" class="space-y-6">

                    <div class="flex justify-between">
                        <div class="flex space-x-2">
                            <div>
                                <flux:button type="submit" variant="primary">{{ __('common.SAVE') }}</flux:button>
                            </div>
                        </div>

                        <div>
                            <flux:modal.trigger name="delete-profile">
                                <flux:button variant="danger">Delete</flux:button>
                            </flux:modal.trigger>

                            <flux:modal name="delete-profile" class="min-w-[22rem] space-y-6">
                                <div>
                                    <flux:heading size="lg">Delete project?</flux:heading>

                                    <flux:subheading>
                                        <p>You're about to delete this project.</p>
                                        <p>This action cannot be reversed.</p>
                                    </flux:subheading>
                                </div>

                                <div class="flex gap-2">
                                    <flux:spacer/>

                                    <flux:modal.close>
                                        <flux:button variant="ghost">Cancel</flux:button>
                                    </flux:modal.close>

                                    <flux:button wire:click="deleteTranslation()" variant="danger">Delete project
                                    </flux:button>
                                </div>
                            </flux:modal>
                        </div>
                    </div>

                </form>

            </flux:tab.panel>
        @endforeach

    </flux:tab.group>
</div>

```

![Image](https://github.com/user-attachments/assets/b267a0f7-4231-42f6-b043-f07df435e17c)

**Comment by jeffchown** [comment] 2024-10-28 23:06
@Hesesses Are you able to provide code that doesn't have any dependencies so people can cut & paste to reproduce and examine the issue?

**Comment by lotje-kinable** [comment] 2024-10-29 08:57
@Hesesses did you try adding wire:key (to the foreach)?

**Comment by Hesesses** [comment] 2024-10-29 09:51
Yes, Didnt help

**Comment by jeffchown** [comment] 2024-10-29 11:05
> > [@Hesesses](https://github.com/Hesesses) Are you able to provide code that doesn't have any dependencies so people can cut & paste to reproduce and examine the issue?
> 
> Updated!

Great, @Hesesses .

I think the issue has something to do with the `flux:modal` being contained in a `flux:tab.panel`.  

I did two things to get it to work, I gave each modal a unique name and I used `@teleport` to move the `<flux:modal>` code outside of the `<flux:tab.panel>`:

```
    <div class="space-y-6">
        <flux:tab.group>
            <flux:tabs wire:model="trans" wire:click="changeTrans" class="overflow-x-auto">
                @foreach (['en','fi','es'] as $language)
                    <flux:tab name="{{ $language }}">
                        {{ $language }}
                    </flux:tab>
                @endforeach

            </flux:tabs>

            @foreach (['en','fi','es'] as $translation)
                <flux:tab.panel :name="$translation">

                    <form wire:submit="saveTranslation" class="space-y-6">

                        <div class="flex justify-between">
                            <div class="flex space-x-2">
                                <div>
                                    <flux:button type="submit" variant="primary">{{ __('common.SAVE') }}</flux:button>
                                </div>
                            </div>

                            <div>
                                <flux:modal.trigger :name='"delete-profile-$translation"'>
                                    <flux:button variant="danger">Delete</flux:button>
                                </flux:modal.trigger>

                                @teleport('body')
                                    <flux:modal :name='"delete-profile-$translation"' class="min-w-[22rem] space-y-6">
                                        <div>
                                            <flux:heading size="lg">Delete project?</flux:heading>

                                            <flux:subheading>
                                                <p>You're about to delete this project.</p>
                                                <p>This action cannot be reversed.</p>
                                            </flux:subheading>
                                        </div>

                                        <div class="flex gap-2">
                                            <flux:spacer/>

                                            <flux:modal.close>
                                                <flux:button variant="ghost">Cancel</flux:button>
                                            </flux:modal.close>

                                            <flux:button wire:click="deleteTranslation()" variant="danger">Delete project
                                            </flux:button>
                                        </div>
                                    </flux:modal>
                                @endteleport
                            </div>
                        </div>

                    </form>

                </flux:tab.panel>
            @endforeach

        </flux:tab.group>
    </div>
```

**Comment by Hesesses** [comment] 2024-10-29 14:12
Thanks @jeffchown!

Is there going to be any "fixes" to be able to do it how I was trying to do it or is this the way to handle modals inside tabs?

**Comment by jeffchown** [comment] 2024-10-29 14:24
You're welcome, @Hesesses !

I don't know re: any 'fixes'.   I'm not part of the Flux team so you'll have to ask @calebporzio or @joshhanley.

That said, I believe the nature of a tab's panel's content being hidden/shown makes it difficult for the modal code to be properly implemented in the DOM.

**Comment by cstisa** [comment] 2024-10-29 16:04
Hi,

I encountered some problems too, trying to add modal in dropdowns on each row of my table, and the @teleport did the trick!

Thanks @jeffchown for this tip!

**Comment by jeffchown** [comment] 2024-10-29 16:38
@cstisa , @Hesesses A pattern I use often to avoid creating multiple modals for the same purpose, is:

- create a Livewire component for the modal (e.g. `DeleteProfileModal`) that has a public property e.g. `id`
- add a listener, to that component, for an e.g. 'open-delete-profile-modal' event that calls a method to set the `id` in the component, initialize whatever data is needed, then open the modal via Flux's `$this->modal('delete-profile-modal')->show();`
- include that component (e.g. `<livewire:delete-profile-modal />`) in whichever Blade files need it, just before the closing `</body>` tag `
- add a button in each row that dispatches the Livewire event, via Alpine, and passes the `id` parameter, e.g.

```
<flux:button
    x-on:click.prevent="Livewire.dispatch('open-delete-profile-modal', { id: '{{ $profile->id }}' })"
    type="button"
    variant="ghost"
    icon="trash"
>
    Delete Profile
</flux:button>
```

This way, I only need one modal (it becomes 'reusable' by each of my table's rows), I know the modal markup code is positioned 'out of the way' near the bottom closing `</body>` tag and I have reduced the overall size and load of my page.

**Comment by calebporzio** [comment] 2024-11-01 16:45
The problem is that you are creating multiple modals of the same name because of the foreach loop. Because of this, triggering one modal is triggering them all and causing weird issues in the browser.

The fix is to "scope" the name of the modal inside the loop like so:

```html
<flux:modal.trigger :name="'delete-profile-'.$translation">
    <flux:button variant="danger">Delete</flux:button>
</flux:modal.trigger>

<flux:modal :name="'delete-profile-'.$translation" class="min-w-[22rem] space-y-6">
    ...
```

I just added a new section to the modal docs to make this clear for folks: https://fluxui.dev/components/modal#unique-modal-names

Thanks!

**Closed by calebporzio** 2024-11-01 16:45 UTC
