### ISSUE TITLE
Conditionally add the invalid property in input.

### ISSUE THREAD

**Issue by nerisonpitogo** [livewire/flux#908] opened 2024-12-21 08:10 UTC
### Flux version

1.0

### Livewire version

3.4

### What is the problem?

Is there a way to conditionally add "invalid" prop in input? 

<flux:input disabled label="Email" />

Ex. 

`<flux:input {{1==1? "invalid":""}} label="Email" />`

### Code snippets

Im making a gasoline station app. 

```

<?php

use Livewire\Volt\Component;
use App\Models\Station\Station;
use Livewire\Attributes\Title;

new #[Title('Calculator')] class extends Component {
    public Station $station;

    public $date;
    public $crew;
    public $numHours;

    public $priceChangeCount = 2;
    public $priceChanges = [];

    public $initialReadings = [];
    public $newPriceReadingsTotal = [];
    public $newPriceReadingsTotalDisplay = [];
    public $newPriceReadings = [];
    public $stationPumpsArray = [];
    public $withError = [];
    public $overallTotal = [];

    public function mount(Station $station)
    {
        $this->station = $station;
        $this->date = date('Y-m-d');

        $this->initializePriceChanges();
    }

    public function initializePriceChanges()
    {
        for ($priceChange = 1; $priceChange <= $this->priceChangeCount; $priceChange++) {
            if (!isset($this->priceChanges[$priceChange])) {
                $this->priceChanges[$priceChange] = ['premium' => 50, 'regular' => 53, 'diesel' => 56];
            }
        }

        foreach ($this->station->pumps as $pump) {
            if (!isset($this->initialReadings[$pump->id])) {
                $this->initialReadings[$pump->id] = null;
            }
            for ($priceChange = 1; $priceChange <= $this->priceChangeCount; $priceChange++) {
                if (!isset($this->newPriceReadings[$priceChange][$pump->id])) {
                    $this->newPriceReadings[$priceChange][$pump->id] = null;
                }
                if (!isset($this->newPriceReadingsTotal[$priceChange][$pump->id])) {
                    $this->newPriceReadingsTotal[$priceChange][$pump->id] = null;
                }
                // newPriceReadingsTotalDisplay
                if (!isset($this->newPriceReadingsTotalDisplay[$priceChange][$pump->id])) {
                    $this->newPriceReadingsTotalDisplay[$priceChange][$pump->id] = null;
                }
            }
        }

        // add the ids of the pumps into the stationPumpsArray
        foreach ($this->station->pumps as $pump) {
            // store in pump->id, pump->tank->gas_type
            $this->stationPumpsArray[] = ['id' => $pump->id, 'gas_type' => $pump->tank->gas_type];
            $this->withError[$pump->id] = [0 => true];
            //iterate price changes withError[pumpId][priceChange]=false
            for ($priceChange = 1; $priceChange <= $this->priceChangeCount; $priceChange++) {
                $this->withError[$pump->id][$priceChange] = true;
            }

            $this->overallTotal[$pump->id] = 0;
        }
    }

    public function with()
    {
        $crews = $this->station->crews()->get();
        return [
            'crews' => $crews,
        ];
    }

    public function addPriceChange()
    {
        $this->priceChangeCount++;
        $this->priceChanges[$this->priceChangeCount] = ['premium' => null, 'regular' => null, 'diesel' => null];

        // Initialize readings for the new price change
        foreach ($this->station->pumps as $pump) {
            $this->newPriceReadings[$this->priceChangeCount][$pump->id] = null;
            $this->newPriceReadingsTotal[$this->priceChangeCount][$pump->id] = null;
            $this->newPriceReadingsTotalDisplay[$this->priceChangeCount][$pump->id] = null;
            $this->withError[$pump->id][$this->priceChangeCount] = false;
            $this->withError[$pump->id][0] = false;
        }
    }

    public function removePriceChange()
    {
        if ($this->priceChangeCount > 1) {
            $this->priceChangeCount--;
            unset($this->priceChanges[$this->priceChangeCount + 1]);
        }
    }

    public function Save()
    {
        // loop withError and check if there is an error
        foreach ($this->withError as $pumpId => $errors) {
            foreach ($errors as $error) {
                if ($error) {
                    Flux::toast(variant: 'danger', heading: 'Error.', text: 'Please check the values.');
                    return;
                }
            }
        }
    }
}; ?>

<div>
    <flux:card>
        <flux:heading size="xl" level="1">Calculator - {{ $station->station_name }}</flux:heading>
        <flux:subheading size="xl" level="1">{{ $station->station_address }}</flux:subheading>
        <flux:separator variant="subtle" class="mt-2" />
        <div class="grid w-full grid-cols-1 gap-4 mt-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            <flux:input class="w-full" type="date" wire:model='date' max="{{ date('Y-m-d') }}"
                label="Date (MM-DD-YYYY)" />

            <flux:select class="w-full" wire:model="crew" placeholder="Choose Crew" searchable variant="listbox"
                clearable label="Crew">
                @foreach ($crews as $crew)
                    <flux:option value="{{ $crew->id }}">{{ $crew->name }}</flux:option>
                @endforeach
            </flux:select>

            <flux:input class="w-full" type="number" wire:model='numHours' max="24" label="Number of Hours" />
        </div>
    </flux:card>

    <flux:card class="mt-2">
        <flux:subheading size="xl" level="1">Price Changes
            <flux:button class="ml-2" variant="primary" wire:click="removePriceChange" icon="minus"
                tooltip="Reduce Price Change">
            </flux:button>
            <flux:button class="" variant="primary" wire:click="addPriceChange" icon="plus"
                tooltip="Increase Price Change">
            </flux:button>
        </flux:subheading>
        <div class="grid w-full grid-cols-1 mt-2">
            <flux:card>

                <flux:table>

                    <flux:rows>

                        @for ($priceChange = 1; $priceChange <= $priceChangeCount; $priceChange++)
                            <livewire:station.calculator.price-input :index="$priceChange" :priceChanges="$priceChanges[$priceChange]"
                                wire:key="price-change-{{ $priceChange }}" />
                        @endfor

                    </flux:rows>
                </flux:table>
            </flux:card>
        </div>
    </flux:card>

    <flux:card class="mt-2">

        <flux:table>
            <flux:columns>
                <flux:column>STA</flux:column>
                <flux:column>INITIAL READING</flux:column>

                @for ($priceChange = 1; $priceChange <= $priceChangeCount; $priceChange++)
                    <flux:column>{{ $priceChange == $priceChangeCount ? 'FINAL READING' : 'READING ' . $priceChange }}
                    </flux:column>
                    <flux:column>TOTAL</flux:column>
                @endfor

                @if ($priceChangeCount > 1)
                    <flux:column>OVERALL TOTAL</flux:column>
                @endif
            </flux:columns>

            <flux:rows x-data="{
                get priceChangeCount() {
                    return $wire.priceChangeCount;
                },
            
                get priceChanges() {
                    return $wire.priceChanges;
                },
            
                get initialReadings() {
                    return $wire.initialReadings;
                },
            
                get newPriceReadings() {
                    return $wire.newPriceReadings;
                },
            
                get newPriceReadingsTotal() {
                    return $wire.newPriceReadingsTotal;
                },
            
                get newPriceReadingsTotalDisplay() {
                    return $wire.newPriceReadingsTotalDisplay;
                },
            
                get stationPumpsArray() {
                    return $wire.stationPumpsArray;
                },
            
                get withError() {
                    return $wire.withError;
                },
            
                get overallTotal() {
                    return $wire.overallTotal;
                },
            
            
                updateValues(pumpId, gastType) {
                    // alert(this.stationPumpsArray);
                    let previousReading = 0;
                    let initialReading = parseFloat(this.initialReadings[pumpId]);
            
                    if (isNaN(initialReading) || initialReading === '') {
                        this.withError[pumpId][0] = true;
                        {{-- add class border border-red-500 to refs tr_pumpId  --}}
                        this.$refs['initial_reading_' + pumpId].classList.add('!border', '!border-red-500');
            
                    } else {
            
                        this.withError[pumpId][0] = false;
                        {{-- remove class border border-red-500 to refs tr_pumpId  --}}
                        this.$refs['initial_reading_' + pumpId].classList.remove('!border', '!border-red-500');
                    }
            
                    let totalOverall = 0;
                    for (let i = 1; i <= this.priceChangeCount; i++) {
                        //priceChanges
                        {{-- get the price for the gas --}}
                        let currentPrice = this.priceChanges[i][gastType];
            
                        {{-- get the readIng per iteration newPriceReadings.1.8 --}}
                        let newReading = parseFloat(this.newPriceReadings[i][pumpId]);
            
                        //if new reading is not null or empty multiply the current price by the new reading and set the value to newPriceReadingsTotal
                        if (newReading >= 0) {
                            if (i == 1) {
                                this.newPriceReadingsTotal[i][pumpId] = ((newReading - initialReading) * currentPrice);
                                {{-- store in 1,230.20 format --}}
                                this.newPriceReadingsTotalDisplay[i][pumpId] = this.newPriceReadingsTotal[i][pumpId].toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
                                totalOverall += this.newPriceReadingsTotal[i][pumpId];
                            } else {
            
                                this.newPriceReadingsTotal[i][pumpId] = ((newReading - previousReading) * currentPrice);
            
                                {{-- store in 1,230.20 format --}}
                                this.newPriceReadingsTotalDisplay[i][pumpId] = this.newPriceReadingsTotal[i][pumpId].toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
                                this.newPriceReadingsTotalDisplay[i][pumpId];
                                totalOverall += this.newPriceReadingsTotal[i][pumpId];
                            }
            
                            {{-- if this.newPriceReadingsTotal[i][pumpId] < 0 meaning negative value add red border to new_reading input --}}
                            if (this.newPriceReadingsTotal[i][pumpId] < 0) {
                                this.withError[pumpId][i] = true;
                                this.$refs['new_reading_' + i + '_' + pumpId].classList.add('!border', '!border-red-500');
                            } else {
                                this.withError[pumpId][i] = false;
                                this.$refs['new_reading_' + i + '_' + pumpId].classList.remove('!border', '!border-red-500');
                            }
            
                            previousReading = newReading;
                        } else {
                            this.withError[pumpId][i] = true;
                            this.$refs['new_reading_' + i + '_' + pumpId].classList.add('!border', '!border-red-500');
                        }
            
                    }
            
                    this.overallTotal[pumpId] = totalOverall.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
                },
            
            
            }" x-init="$watch('priceChanges', (value) => {
                stationPumpsArray.forEach((pump) => {
                    updateValues(pump.id, pump.gas_type);
                });
                alert(1);
            });
            
            Livewire.on('load', () => {
                stationPumpsArray.forEach((pump) => {
                    updateValues(pump.id, pump.gas_type);
                });
                alert(2);
            });
            
            Livewire.on('update', () => {
                stationPumpsArray.forEach((pump) => {
                    updateValues(pump.id, pump.gas_type);
                });
                alert(3);
            });">

                <flux:input x-html:invalid="1 == 1" label="Email" />


                @foreach ($station->pumps as $pump)
                    <flux:row>
                        <flux:cell>{{ $pump->pump_short_name }}</flux:cell>

                        {{-- <flux:cell x-data="{ withError: $wire.withError[{{ $pump->id }}] }" x-init="alert(withError)" class="bg-red-100">
                            <flux:input x-on:keyup="updateValues({{ $pump->id }}, '{{ $pump->tank->gas_type }}')"
                                type="number" min="1" wire:model='initialReadings.{{ $pump->id }}'>
                            </flux:input>
                        </flux:cell> --}}

                        <div>
                            <flux:cell>
                                <flux:input class="!min-w-36" x-ref='initial_reading_{{ $pump->id }}'
                                    x-on:keyup="updateValues({{ $pump->id }}, '{{ $pump->tank->gas_type }}')"
                                    x-on:change="updateValues({{ $pump->id }}, '{{ $pump->tank->gas_type }}')"
                                    type="number" min="1" wire:model="initialReadings.{{ $pump->id }}">
                                </flux:input>
                            </flux:cell>
                        </div>

                        @for ($priceChange = 1; $priceChange <= $priceChangeCount; $priceChange++)
                            <flux:cell>



                                <flux:input class="!min-w-36" type="number" min="1"
                                    x-ref='new_reading_{{ $priceChange }}_{{ $pump->id }}'
                                    x-on:keyup="updateValues({{ $pump->id }}, '{{ $pump->tank->gas_type }}')"
                                    x-on:change="updateValues({{ $pump->id }}, '{{ $pump->tank->gas_type }}')"
                                    wire:model='newPriceReadings.{{ $priceChange }}.{{ $pump->id }}'>
                                </flux:input>

                            </flux:cell>

                            <flux:cell>
                                <flux:input class="!min-w-36" type="text" readonly variant="filled"
                                    wire:model='newPriceReadingsTotalDisplay.{{ $priceChange }}.{{ $pump->id }}'>
                                </flux:input>
                            </flux:cell>
                        @endfor
                        @if ($priceChangeCount > 1)
                            <flux:cell>
                                <flux:input class="!min-w-36" type="text" readonly variant="filled"
                                    wire:model='overallTotal.{{ $pump->id }}'>
                                </flux:input>
                            </flux:cell>
                        @endif
                    </flux:row>
                @endforeach
            </flux:rows>
        </flux:table>

    </flux:card>

    <flux:button wire:click='Save' variant="primary" class="mt-2">
        SAVE
    </flux:button>
</div>

```

### How do you expect it to work?

Using alpineJS I can add red border to the inputs but when save button it is removed.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by ju5t** [comment] 2024-12-21 10:02
Can you share a much shorter and copy/pasteable version of what you want to do?

This works for me:

```blade
<flux:input label="Email" :invalid="true" />
```

**Comment by joshhanley** [comment] 2024-12-22 21:44
@nerisonpitogo thanks for reporting! @ju5t is correct, you should use Blade's `:invalid=""` syntax and pass in a PHP expression that can evaluate to true or false.

In future please don't share all of your code, any long code snippets like this will be closed as they don't clearly show the Flux bug. Only share a short code snippet we can copy and paste into our own apps with steps to reproduce. Be sure to include any Blade variable definitions that are used and use a little code as possible to reproduce the issue. Thanks!

**Closed by joshhanley** 2024-12-22 21:44 UTC
