### ISSUE TITLE
missing import in theme builder

### ISSUE THREAD

**Issue by webpatser** [livewire/flux#927] opened 2024-12-25 08:14 UTC
### Flux version

v1.1.2

### Livewire version

v3.5.18

### What is the problem?

When using the theme builder. If you copy paste everything in the correct files, there is an error.

In the tailwind file you also need to import `import colors from 'tailwindcss/colors';`

Maybe thats a good idea to also mention that in the builder..

Besides that, all awesome!

Thank you

### Code snippets

so now it's

```
@layer base {
    :root {
        --color-accent: var(--color-zinc-800);
        --color-accent-content: var(--color-zinc-800);
        --color-accent-foreground: var(--color-white);
    }

    .dark {
        --color-accent: var(--color-white);
        --color-accent-content: var(--color-white);
        --color-accent-foreground: var(--color-zinc-800);
    }
}
```

It should be

```
import colors from 'tailwindcss/colors';

@layer base {
    :root {
        --color-accent: var(--color-zinc-800);
        --color-accent-content: var(--color-zinc-800);
        --color-accent-foreground: var(--color-white);
    }

    .dark {
        --color-accent: var(--color-white);
        --color-accent-content: var(--color-white);
        --color-accent-foreground: var(--color-zinc-800);
    }
}
```

### How do you expect it to work?

Nothing to see here.. 

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by Jaiieq** [comment] 2024-12-26 15:21
The colors import goes in your tailwind.config.js file.  In your example, you are adding it to your app.css file.

**Comment by joshhanley** [comment] 2024-12-26 22:45
@webpatser thanks for reporting! Yep, @Jaiieq is correct, the import goes in your `tailwind.config.js` file, not your `app.css`. So the instructions are correct. I'm going to close this, but if you are experiencing an issue caused by this, then feel free to open a new issue and describe the problem you're having so we can investigate.

**Closed by joshhanley** 2024-12-26 22:45 UTC
